title: Welcome to the world of Boulder Bill!
author: William Spears
email: William.w.spears@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello!
  My name is William but my friends call me Boulder Bill.
  This is my website where I will be learning how to write code and create programs. I am also working on a new youtube channel!

theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
